server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5431/memodb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.keycloak.client-id=memoto-client
spring.security.oauth2.client.registration.keycloak.client-secret=OFZU6DWBWSUTPuZRsCccHjUXfSxLjo74
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8081/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/memoto-realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/memoto-realm
