spring.datasource.url=jdbc:postgresql://localhost:5431/mementodb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always