version: '3.8'
# https://www.baeldung.com/spring-boot-postgresql-docker#create_project
services:
  db:
    image: 'postgres:16'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres