server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/memodb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: memoto-client
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/memoto-realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/memoto-realm